v1
zYoma/go_keeper- pull request #1
Opened 2024-05-17 13:01 UTC by zYoma

2024-05-22 14:15 UTC, bambruysk reviewed
Начало положено

Нужно доработать в части клиента, он должен быть более самостоятельным, выдерживать обрывы соединений, хранить копию данных у себя ( желательно) 

Сервер должен хранить и пользователя и его данные долгосрочно и выдерживать отключение и подключение и собственную перезагрузку. Хранить стейт пользователя в памяти сервера - это обычно история про игры, биржи и другие подобные решения


Раз уж мы храним чувствительные данные, то нужно обеспечивать хотя бы авторизацию 

Если хочется повозиться со стримами, то я бы предложил немного другую схему

Клиент запускается и аутентифицируется на сервере
Открывается стрим на сервер (не забываем авторизацию)
В случае появления новых данных в клиенте, отправляется сообщение на сервер
Остальные клиенты этого же владельца получают обновления данных (желательно не целиком все данные, а именно апдейт)

2024-05-22 14:15 UTC, bambruysk commented on Makefile
> +BINARY_NAME=shortener
почему shortener?

2024-05-22 14:15 UTC, bambruysk commented on internal/server/app/command_handler.go
> +	client := &client{stream: stream, ch: make(chan *pb.CommandMessage, 100), done: make(chan struct{}), state: service.CONNECTED}
лучше сделать конструктор для таких штук

2024-05-22 14:15 UTC, bambruysk commented on internal/server/app/command_handler.go
> +			case service.AUTHORIZATE:
почему этот стейт называется AUTHORIZATE -  хотя в нем не выполняется авторизация?

2024-05-22 14:15 UTC, bambruysk commented on internal/server/app/command_handler.go
> +				s.clients[username] = client
клиенты хранятся просто в мапе?

2024-05-22 14:15 UTC, bambruysk commented on internal/server/app/command_handler.go
> +				case "3": // карта
Здесь не хватает дефолтной ветки

2024-05-22 14:15 UTC, bambruysk commented on internal/server/app/command_handler.go
> +func (s *server) clientProcessing(client *client, recvChan chan *pb.CommandMessage, stopRecvChan chan struct{}, errChan chan error) error {
Как эта схема будет работать с несколькими клиентами одного владельца?

2024-05-22 14:15 UTC, bambruysk commented on internal/server/app/command_handler.go
> +				err := s.createData(msg.Message, username, createdType)
то есть данные передаются в открытом виде?

2024-05-22 14:15 UTC, bambruysk commented on internal/server/app/command_handler.go
> +					client.state = service.CREATE_DATA
Вот это все общение с клиентом - лучше вывести в клиент. 
У нас требуется 

> доступ к приватным данным по запросу.

то есть приложение должно сделать один запрос,  и получить ответ. 

Стримы это интересно, но здесь это как-то неуместно, и выглядит коряво в результате. Обрывы соединений и прочее, как мы будем с этим справляться?

2024-05-22 14:15 UTC, bambruysk commented on internal/server/storage/sqlite/sqlite.go
> +	defer s.mutex.Unlock()
Это похоже единственное место где он блокируется,тогда зачем он?  Может лучше sync.Once?

2024-05-22 14:15 UTC, bambruysk commented on internal/server/storage/storage.go
> +}
А зачем этот интерфейс?

2024-05-22 14:15 UTC, bambruysk commented on internal/server/service/enums.go
> +	TEXT
У нас еще бинарные данные есть, например файлы

2024-05-22 14:15 UTC, bambruysk commented on proto/keeper.proto
> +    string username = 1;
То есть авторизация просто по юзернейму?

2024-05-22 14:16 UTC, bambruysk requested changes
Возвращаю

2024-05-25 05:39 UTC, zYoma commented on Makefile
> +BINARY_NAME=shortener
Исправил

2024-05-25 05:39 UTC, zYoma commented on internal/server/app/command_handler.go
> +	client := &client{stream: stream, ch: make(chan *pb.CommandMessage, 100), done: make(chan struct{}), state: service.CONNECTED}
Сделал конструктор

2024-05-25 05:42 UTC, zYoma commented on internal/server/app/command_handler.go
> +			case service.AUTHORIZATE:
Мне показалось, ты не понял как у меня это работает. У меня есть аунтификация и авторизация.
Пока пользователь не войдет используя свой логин/пароль и не получит идентификатор на основе своего логина, он не сможет получить доступ к данным.
Я записал 2 мин видео с демонстрацией работы, пожалуйста, потрать 2 мин на просмотр.
https://www.youtube.com/watch?v=3tvnidVqjpY

2024-05-25 05:45 UTC, zYoma commented on internal/server/app/command_handler.go
> +				s.clients[username] = client
Клиенты хранятся в таблице users. Там хранится логин и хеш пароля. В мапе хронятся подключенные сессиии в данный момент(стримы). Когда пользоватль подключается, его стрим добавляется в мапу, это нужно, в частности, для того, чтобы уведомить другого клиента одного и того же пользователя при добавлении данных.
Когда пользователь отключается. его сессия удаляется из мапы.

2024-05-25 05:45 UTC, zYoma commented on internal/server/app/command_handler.go
> +				case "3": // карта
Добавил

2024-05-25 05:49 UTC, zYoma commented on internal/server/app/command_handler.go
> +func (s *server) clientProcessing(client *client, recvChan chan *pb.CommandMessage, stopRecvChan chan struct{}, errChan chan error) error {
Продемонстрировал в видео https://www.youtube.com/watch?v=3tvnidVqjpY
Один и тот же пользователь может подключиться с разных устройств и при этом он будет иметь доступ к своим данным на каждом устройстве, сможет создавать данные (уведомления о появлении новых данных направляются во все стримы одного пользователя за исключением того где выполнено действие)

2024-05-25 05:52 UTC, zYoma commented on internal/server/app/command_handler.go
> +				err := s.createData(msg.Message, username, createdType)
Ок. 
1) Данные хранятся в БД в зашифрованном виде. Перед сохранением в таблицу они шифруются. После извлечения из таблицы и отправке пользователю - расшифровываются.
2)Я добавил  TLS шифрование между клиентом и сервером. Клиент подключается с сертификатом. Подключение защищено.

2024-05-25 05:53 UTC, zYoma commented on internal/server/app/command_handler.go
> +					client.state = service.CREATE_DATA
Нет. Давай оставим мой вариант. Это не продуктовый код. Экспериментальный.

2024-05-25 05:53 UTC, zYoma commented on internal/server/storage/sqlite/sqlite.go
> +	defer s.mutex.Unlock()
Переделал на sync.Once

2024-05-25 05:53 UTC, zYoma commented on internal/server/storage/storage.go
> +}
Согласен. Убрал

2024-05-25 05:54 UTC, zYoma commented on internal/server/service/enums.go
> +	TEXT
Да. Я проигнорировал это требование, так как оно мало чем отличается в реализации от текстовых данных. 
Вместо этого я добавил возможность сохранения данных, что по заданию является опциональным. Компенсировал одно требование другим)

2024-05-25 05:56 UTC, zYoma commented on proto/keeper.proto
> +    string username = 1;
Нет. Если ты посмотришь на протофайл, там для авторизации есть отдельный метод
rpc Login(LoginRequest) returns (LoginResponse);
где передается логи и пароль.

Стрим открывается только после успешной авторизации.

2024-06-02 18:48 UTC, bambruysk requested changes
Нужно добавить работу с бинарными данными  ( пусть копипастой текста) и метадатой - эт таки обязательные требования

2024-06-02 18:48 UTC, bambruysk commented on internal/server/app/command_handler.go
> +				s.clients[username] = client
Такая схема не очень кмк устойчива к перезагрузкам и перевыкаткам - сессии лучше хранить в  БД или редисе

2024-06-02 18:48 UTC, bambruysk commented on internal/server/app/command_handler.go
> +			case service.AUTHORIZATE:
Я чисто про названия стейтов

Кстати в видео нет работы с метаданными записей

2024-06-02 18:48 UTC, bambruysk commented on internal/server/app/command_handler.go
> +					client.state = service.CREATE_DATA
Слишком много отклонений

Сначала думал забанить, но потом решил - что почему бы и нет

Только стоит добавить описание всех трейдоффов в этом проекте и отклонений

2024-06-02 18:48 UTC, bambruysk commented on internal/server/app/command_handler.go
> +			if err != nil {
Здесь мб ретрай какой добавить?

2024-06-03 07:04 UTC, zYoma commented on internal/server/app/command_handler.go
> +			case service.AUTHORIZATE:
Добавил возможность добавить метаданные для каждого типа данных

2024-06-03 07:05 UTC, zYoma commented on internal/server/app/command_handler.go
> +				s.clients[username] = client
Добавил хранение состояния клиента в БД

2024-06-03 07:06 UTC, zYoma commented on internal/server/app/command_handler.go
> +			if err != nil {
Добавил ретраи

2024-06-11 12:30 UTC, edylcrm approved these changes

2024-06-11 12:30 UTC, edylcrm commented on internal/client/app/login.go
> +	go s.getData(stream)
Я бы все таки предложил просто создавать wg без add(2) в конструкторе, а wg.Add() добавлять здесь где создаются горутины и делал бы это примерно вот так 
```
wg.Add(1)
go func() {
    defer wg.Done()
    s.getData()
}()

wg.Wait()
```
Так более явно и понятно где используется waitgroup. В текущей реализации сложновато отслеживать логику с waitgroup

2024-06-11 12:30 UTC, edylcrm commented on internal/server/app/command_handler.go
> +	s.clients[clientID] = client
Здесь не нужен mutex?

2024-06-12 09:51 UTC, merged